name: dl_stack

networks:
  starr:
    external: true
  qbit:
    external: true
  dozzle:
    external: true

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    environment:
      - PUID=${PUID:?error}
      - PGID=${PGID:?error}
      - TZ=${TZ:?error}
    volumes:
      - ${APPDATA:?error}/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped 
    networks:
      - starr
      - qbit
      - dozzle
      
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.0
    container_name: qbittorrent
    hostname: qbittorrent
    environment:
      - PUID=${PUID:?error}
      - PGID=${PGID:?error}
      - TZ=${TZ:?error}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${APPDATA}/qbittorrent/config:/config
      - ${MEDIA_SHARE1:?error}/data/torrents:/data/torrents
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
        - qbit
        - dozzle

  qui:
    image: ghcr.io/autobrr/qui:latest
    container_name: qui
    restart: unless-stopped
    ports:
      - 7476:7476
    volumes:
      - ${APPDATA:?error}/qui/config:/config
      - ${MEDIA_SHARE1:?error}/data/torrents:/data/torrents
    depends_on:
      - qbittorrent
    networks:
      - qbit
      - dozzle