name: dl_stack

networks:
  starr:
    external: true
  qbit:
    external: true

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID:?error}
      - PGID=${PGID:?error}
      - TZ=${TZ:?error}
    volumes:
      - ${APPDATA:?error}/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped 
    networks:
      - starr
      - qbit
      
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.0
    container_name: qbittorrent
    environment:
      - PUID=${PUID:?error}
      - PGID=${PGID:?error}
      - TZ=${TZ:?error}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${APPDATA}/qbittorrent/config:/config
      - ${MEDIA_SHARE:?error}/data/torrents:/data/torrents #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
        - qbit

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
      - LANG=en_GB
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    networks:
        - qbit

  huntarr: #finds missing files 
    image: huntarr/huntarr:latest
    container_name: huntarr
    restart: always
    ports:
      - "9705:9705"
    volumes:
      - ${APPDATA}/huntarr:/config
    environment:
      - TZ=${TZ}
    networks:
      - starr
      - qbit


  decluttarr: # Remove slow and stalled torrents
    image: ghcr.io/manimatter/decluttarr:latest
    container_name: decluttarr
    restart: always
    networks:
      - qbit
      - starr
    environment:
      - TZ=${TZ}
      - PUID=${PUID:?error}
      - PGID=${PGID:?error}

      - LOG_LEVEL=INFO
      - TEST_RUN=True
      - TIMER=10
      # IGNORED_DOWNLOAD_CLIENTS: >
      #   - emulerr
      # SSL_VERIFICATION: true
      # PRIVATE_TRACKER_HANDLING: "obsolete_tag"
      # PUBLIC_TRACKER_HANDLING: "remove"
      # OBSOLETE_TAG: "Obsolete"
      # PROTECTED_TAG: "Keep"

      # # --- Optional: Job Defaults ---
      # You can use these to set those parameters across all jobs. If you don't specify it here, the defaults set by system will be used
      # If you set job-specific parameters (further down below), they will override these settings.
      - max_strikes=10
      - MIN_DAYS_BETWEEN_SEARCHES=14
      - MAX_CONCURRENT_SEARCHES=6

      # # --- Jobs (short notation) ---
      # If you want to go with the most basic settings, you can just turn them all on:
      # REMOVE_BAD_FILES: |
      #   keep_archives: True
      # REMOVE_BAD_FILES:
        # keep_archives: True
      # REMOVE_FAILED_DOWNLOADS: True
      # REMOVE_FAILED_IMPORTS: True
      # REMOVE_METADATA_MISSING: |
      #   max_strikes: 3
      # REMOVE_MISSING_FILES: True
      # REMOVE_ORPHANS: True
      # REMOVE_SLOW: |
      #   min_speed: 10
      #   max_strikes: 10
      # REMOVE_STALLED: |
      #   max_strikes: 10
      # REMOVE_UNMONITORED: True
      # SEARCH_BETTER: True
      # SEARCH_MISSING: True
      # DETECT_DELETIONS: True

      # # --- OR: Jobs (with job-specific settings) ---
      # Alternatively, you can use the below notation, which for certain jobs allows you to set additional parameters
      # As written above, these can also be set as Job Defaults so you don't have to specify them as granular as below.
      #REMOVE_BAD_FILES: |
      #  keep_archives: True
      #REMOVE_FAILED_DOWNLOADS: True
      #REMOVE_FAILED_IMPORTS: |
      #  message_patterns:
      #    - "Not a Custom Format upgrade for existing*"
      #    - "Not an upgrade for existing*"
      #    - "*Found potentially dangerous file with extension*"
      #    - "Invalid video file*"
      #    - "No files found are eligible for import*"
      #    - "One or more episodes expected in this release were not imported or missing from the release"
      #REMOVE_METADATA_MISSING: |
      #  max_strikes: 10
      #REMOVE_MISSING_FILES: True
      #REMOVE_ORPHANS: True
      #REMOVE_SLOW: |
      #  min_speed: 10
      #  max_strikes: 100
      #REMOVE_STALLED: |
      #  max_strikes: 10
      #REMOVE_UNMONITORED: True
      #SEARCH_UNMET_CUTOFF: |
      #  min_days_between_searches: 7
      #  max_concurrent_searches: 3
      #SEARCH_MISSING: |
      #  min_days_between_searches: 7
      #  max_concurrent_searches: 3
      #DETECT_DELETIONS: true

      # --- Instances ---
      SONARR: >
        - base_url: "http://10.1.1.190:8989"
          api_key: "$SONARR_API_KEY"

      RADARR: >
         - base_url: "http://10.1.1.190:7878"
          api_key: "$RADARR_API_KEY"

      # --- Download Clients ---
      QBITTORRENT: >
        - base_url: "http://10.1.1.190:8080"
          username: "$QBIT_USERNAME" # (optional -> if not provided, assuming not needed)
          password: "$QBIT_PASSWORD" # (optional -> if not provided, assuming not needed)
        #  name: "qBittorrent main" # (optional -> if not provided, assuming "qBittorrent". Must correspond with what is specified in your *arr as download client name)
 
    volumes:
      # - $DOCKERDIR/appdata/decluttarr/logs:/app/logs # Uncomment to get logs in text file, too      
      - ${MEDIA_SHARE:?error}/data:/data # If you use detect_deletions, add the identical mount paths that you use in your sonarr/radarr instances. This may be different to this example!